config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails, only: %i[new create index show] do
    resources :doses, only: %i[new create]
  end

  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :ingredient, :cocktail, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses #, dependent: :restrict_with_error

  validates :name, presence: true, uniqueness: true

  scope :ordered, -> { order(name: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all.order(name: :asc)
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail), notice: "Cocktail <strong>#{@cocktail.name}</strong> was created successfully."
    else
      render :new
    end
  end

  private

  def cocktails_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, except: %i[destroy]

  # get /cocktails/:cocktail_id/doses/new
  def new
    @dose = Dose.new
  end

  # post /cocktails/:cocktail_id/doses
  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  # delete /doses/:id
  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktail_path(@dose.cocktail), alert: 'Ingredient deleted!'
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<% if @cocktails.any? %>
  <h3>List of cocktails</h3>

  <ul>
    <% @cocktails.each do |cocktail| %>
      <li>
        <%= link_to cocktail.name, cocktail_path(cocktail) %>
        <%#= cl_image_tag("https://res.cloudinary.com/lucien-andrieux/image/upload/v1604664825/knlm8xz3nfs8rzokv3ps.jpg",
        width: 400, height: 300, crop: :fill) %>
      </li>
    <% end %>
  </ul>
  <strong><%= link_to 'add new cocktail', new_cocktail_path %></strong>
<% else %>
  <h3>Bummer 😿</h3>
  <p class="empty-state">
    You don't have any cocktails yet. Get the party started by
    <strong><%= link_to 'adding your first one now', new_cocktail_path %></strong>!
  </p>
<% end %>

app/views/cocktails/new.html.erb
<h2>New cocktail</h2>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name, input_html: { autocomplete: 'off' } %>
  <%= f.input :photo, as: :file %>
  <%= link_to 'Cancel', cocktails_path, class: 'btn btn-outline-secondary' %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/cocktails/show.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice.html_safe %>

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<h2><%= @cocktail.name %></h2>

<% if @cocktail.photo.attached? %>
  <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
<% else %>
  <p>No image has been provided yet.</p>
<% end %>

<div class="mb-4">
  <%= link_to cocktails_path do %>
    &larr; Back to list
  <% end %>
</div>

<h3>Ingredients:</h3>

<% if alert.present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= alert.html_safe %>

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if @cocktail.doses.any? %>
  <ul>
    <% @cocktail.doses.each do |dose| %>
      <li>
        <%= dose.description %> <%= dose.ingredient.name %>
        <%= link_to dose_path(dose), method: :delete,
          data: { confirm: 'Really?!', toggle: 'tooltip', placement: 'top' },
          title: 'Delete ingredient',
          class: 'text-danger' do %>
          <small><i class="fa fa-trash"></i></small>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="empty-state">
    No ingredients added, please use the button below to add new ingredients to
    your cocktail.
  </p>
<% end %>

<div>
  <%= link_to new_cocktail_dose_path(@cocktail), class: 'btn btn-sm btn-outline-secondary' do %>
    <i class="fa fa-plus"></i> Add ingredient dose
  <% end %>
</div>

app/views/doses/new.html.erb
<h2>New ingredient dose</h2>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient, collection: Ingredient.ordered %>

  <%= link_to 'Cancel', cocktail_path(@cocktail), class: 'btn btn-outline-secondary' %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🍹 Mr Cocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container">
        <%= link_to 'Mr Cocktail! 🍹', root_path, class: 'navbar-brand' %>
        <%= link_to new_cocktail_path, class: 'btn btn-sm btn-outline-primary' do %>
          <i class="fa fa-plus"></i> Add new cocktail
        <% end %>
      </div>
    </nav>

    <div class="container mt-5">
      <%= yield %>

      <footer class="mt-5">
        &copy; <%= Date.today.year %> Lucien Andrieux All Rights Reserved
      </footer>
    </div>
  </body>
</html>